---
# This Playbook is used
# for testing containers on Testing Farm Fedora

- hosts: all
  vars_files:
    - "group_vars/fedora"

  roles:
    - role: epel_repo
    - role: common_tools
    - role: services
    - role: clone_repos
  become: true
  become_user: root
