---
# This Playbook is used
# for testing sclorg-testing-farm

- name: Testing sclorg-testing-farm repo is everything is present in host provided by Testing Farm
  hosts: "{{ hosts | default('localhost') }}"
  vars:
    os_test: "{{ lookup('env', 'OS') }}"
    gpu: "{{ lookup('env', 'GPU') }}"
    package_names_all:
      - git
      - make
      - podman-docker
      - podman
      - jq
    package_names_c9s:
      - golang-github-cpuguy83-md2man
      - s-nail
      - ansible
      - python3.12
      - python3.12-pytest
      - python3.12-pip
    package_names_c10s:
      - golang-github-cpuguy83-md2man
      - s-nail
      - ansible-core
      - python3
      - python3-pytest
      - python3-pip
    package_names_fedora:
      - acl
      - libseccomp-devel
      - openssl
      - golang-github-cpuguy83-md2man
      - s-nail
      - ansible
      - python3
      - python3-pytest
      - python3-pip
    package_names_image_mode_c9s:
      - podman-bootc
    package_names_gpu_fedora:
      - pciutils
      - hwdata
      - ansible
    files_to_check_fedora:
      - /etc/containers/nodocker
    files_to_check_c9s:
      - /etc/containers/nodocker
    files_to_check_c10s:
      - /etc/containers/nodocker
    output_check_gpu_fedora_nvidia:
      - { command: 'lspci -mm', device_name: '{{ gpu }}', vendor_name: 'NVIDIA' }
    pip_check_install:
      - container-ci-suite

  tasks:
    - debug: msg="{{ os_test }}"
    - block:
        - name: Check if listed package is installed on CentOS Stream 9
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_c9s }}"
        - name: Check if files are present on CentOS Stream 9
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_c9s }}"
        - name: Check if pip package is present on C9S
          include_tasks: ./tasks/check_pip_package_present.yml
          loop: "{{ pip_check_install }}"
      when: (os_test is defined) and (os_test == "centos-stream-9-plan")

    - block:
        - name: Check if listed package is installed on Image mode CentOS Stream 9
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_image_mode_c9s }}"
        - name: Check if files are present on CentOS Stream 9
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_c9s }}"
      when: (os_test is defined) and (os_test == "image-mode-c9s")

    - block:
        - name: Check if listed package is installed on CentOS Stream 10
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_c10s }}"
        - name: Check if files are present on CentOS Stream 10
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_c10s }}"
        - name: Check if pip package is present on C10S
          include_tasks: ./tasks/check_pip_package_present.yml
          loop: "{{ pip_check_install }}"
      when: (os_test is defined) and (os_test == "centos-stream-10-plan")

    - block:
        - name: Check if listed package is installed on Fedora
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_fedora }}"
        - name: Check if file {{ item }} exists
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_fedora }}"
        - name: Check if pip package is present on Fedora
          include_tasks: ./tasks/check_pip_package_present.yml
          loop: "{{ pip_check_install }}"
      when: (os_test is defined) and (os_test == "fedora")

    - block:
        - name: Check if listed package is installed on Fedora
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_fedora + package_names_gpu_fedora }}"
        - name: Check if file {{ item }} exists
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_fedora }}"
        - name: Check if output {{ item }} exists
          include_tasks: ./tasks/check_output_command.yml
          loop: "{{ output_check_gpu_fedora_nvidia }}"
      when: (os_test is defined) and (os_test == "gpu-fedora")
