- name: Get command output
  shell: "{{ item.command }}"
  register: stat_result

- debug: var=stat_result

- name: Check if required string 'vendor_name' is present in output
  shell: "grep {{ item.vendor_name }} '{{ stat_result.stdout }}'"
  register: vendor_result

- debug: var=vendor_result

- name: Fail if output of command {{ item.common }} does not have {{ item.vendor_name }}
  fail: msg="This host {{ os_test }} does not contain file {{ item.vendor_name }}"
  when: not vendor_result.stat.exists

- name: Check if required string 'device_name' is present in output
  shell: "grep {{ item.device_name }} '{{ device_result.stdout }}'"
  register: device_result

- name: Fail if output of command {{ item }} is not present
  fail: msg="This host {{ os_test }} does not contain file {{ item.device_name }}"
  when: not device_result.stat.exists
