---
- name: Install basic tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - make
- name: Install CentOS Stream 9 packages
  package:
    name: "{{ item }}"
    state: latest
    validate_certs: no
    disable_gpg_check: true
  with_items:
    - podman
    - podman-docker
  when: releasever < 30
